# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/versions.html
	minecraft_version=1.20.1
	yarn_mappings=1.20.1+build.10
	loader_version=0.18.4

# Mod Properties
    mod_version=1.4.13+utopia.0.10.11
    maven_group=dev.utopia
    archives_base_name=utopiacore
    
# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api (or https://fabricmc.net/versions.html)
	fabric_version=0.92.2+1.20.1
	cloth_config_version=11.0.99
	mod_menu_version=7.0.0
